import CustomerCard from '@/components/cards/customer'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Octoplus Developers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Octoplus Developers</h1>
        <CustomerCard
          Name="Wilmy Danguya"
          Feedback={
            'Existêm diversas vantagens para escolheres a Octoplus Developers, porém iremos apenas focar em 3 grandes beneficios'
          }
          Role={'Fundador da Octoplus'}
        />
      </main>
    </>
  )
}
